### ISSUE TITLE
Real world use cases?

### ISSUE THREAD

**Issue by firesofmay** [irresponsible/anarchy#1]
Hi,

I am not clear what are the real world use cases for this DSL?
Can you perhaps add such examples in readme or maybe add external links to them?
Thanks

**Comment by jjl** [comment]
I do plan to, it's just that this library didn't exist at all last week!

The important bit of the documentation that's there at the moment is the images of the tables, which is the sort of interface you should expect to be able to achieve on top of this.

To give you a concrete example, I wrote this to support pricing rules for a booking engine. For example, peak season is twice the price of off-peak, fridays and saturdays incur a 10% premium etc.

So what we can do for that is for the event, we can prepare a list of facts about the singular potential booking and put them in a map (including the season the date works out to be according to their booking rules etc.). The user interface can then have a dynamically growing list of conditions and actions where you pick a subject (e.g. "season", "day of week"), a predicate/operand and any arguments.

So that's it. I don't consider it a DSL, it's just a simple matching engine. I don't expect you to write the rules manually, i expect you to generate them (they're just data!) from information provided by a user on a GUI of some kind that shows these tables.

You may find it interesting to study the DTRules documentation a little - although note that the site is really not in good shape, errors all over it, some pages don't work at all. This page in particular is the one that helped me see the point: [Decision Tables](http://www.dtrules.com/newsite/?p=90).

Of course if this has whetted your appetite, I'd be more than happy to accept a PR with some better examples :)

**Comment by firesofmay** [comment]
Okay thanks :)

**Comment by jjl** [comment]
@firesofmay I have just updated the README. What do you think now?

**Comment by jjl** [comment]
I've now added [another example](https://github.com/irresponsible/anarchy/blob/master/gilded_rose.clj) to the repository which I think resolves this issue.
